# Generated by Django 4.2.27 on 2026-01-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('prayer', '기도'), ('word', '말씀 읽기'), ('transcribe', '성경 필사'), ('qt', 'QT'), ('other', '기타')], max_length=20),
        ),
    ]
